name: Schengen Visa Bot

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  check-slots:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Cek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Kutuphaneleri Yukle
        run: |
          pip install -r requirements.txt

      - name: Botu Calistir
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          VFS_EMAIL: ${{ secrets.VFS_EMAIL }}
          VFS_PASSWORD: ${{ secrets.VFS_PASSWORD }}
          COUNTRY: "Poland"
          CITY: "Istanbul"
        run: python bot.py
